root: true

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

env:
  browser: true
  node: true
  commonjs: true
  es6: true
  es2016: true
  es2017: true
  es2018: true
  es2019: true
  es2020: true
  es2021: true
  es2022: true
  es2023: true
  es2024: true

rules:
  semi: "error"
  no-shadow:
    - "off"
    - builtinGlobals: true
      hoist: "all"

overrides:
  - files:
      - "*.js"
      - "*.mjs"
      - "*.cjs"
      - "*.jsx"
    rules:
      no-unused-vars:
        - "error"
        - args: "all"
          argsIgnorePattern: "^_"
          caughtErrors: "all"
          caughtErrorsIgnorePattern: "^_"
          destructuredArrayIgnorePattern: "^_"
          varsIgnorePattern: "^_"
          ignoreRestSiblings: true

  - files:
      - "*.ts"
      - "*.mts"
      - "*.cts"
      - "*.tsx"
    rules:
      "@typescript-eslint/explicit-function-return-type": "error"
      "@typescript-eslint/no-explicit-any": "error"
      "@typescript-eslint/no-shadow": "off"
      "@typescript-eslint/no-empty-object-type": "error"
      "@typescript-eslint/no-inferrable-types":
        - "off"
        - ignoreParameters: true
          ignoreProperties: true
      "@typescript-eslint/no-unused-vars":
        - "error"
        - args: "all"
          argsIgnorePattern: "^_"
          caughtErrors: "all"
          caughtErrorsIgnorePattern: "^_"
          destructuredArrayIgnorePattern: "^_"
          varsIgnorePattern: "^_"
          ignoreRestSiblings: true
