extends:
  - "stylelint-config-standard"
  - "stylelint-config-standard-scss"
  - "stylelint-config-html"

rules:
  color-named: always-where-possible

overrides:
  - files:
      - "*.html"
      - "*.vue"
      - "*.astro"
      - "*.svelte"
    customSyntax: "postcss-html"

  - files:
      - "*.scss"
    customSyntax: "postcss-scss"
