target-version = "py314"
indent-width = 4
line-length = 120
respect-gitignore = true
show-fixes = true
fix = true
src = ["src", "test"]

[format]
# Configures indentation with either spaces or tabs
indent-style = "space"
# Configures single or double quotes for strings
quote-style = "double"
# Configures the quote style for nested strings inside interpolated string expressions
nested-string-quote-style = "alternating"
# Enables respecting magic trailing commas or not
skip-magic-trailing-comma = true
# The character Ruff uses at the end of a line
line-ending = "lf"
# Enables reformatting of code snippets in docstrings
docstring-code-format = true
# Formats all docstring code snippets with a line length of int or dynamic number
docstring-code-line-length = "dynamic"
